<?php

/**
 * Sample 4 - Setting Metadata, Reloading, and Rendering as Paragraph with Custom Style
 *
 * This sample demonstrates:
 * 1. How to set and save document metadata
 * 2. How to reload the document and display metadata as styled Paragraph content
 */

use OdtTemplateEngine\OdtTemplate;
use OdtTemplateEngine\Elements\Paragraph;

require_once dirname(__DIR__, 3) . '/vendor/autoload.php';

// [1] Initialize a new template instance
$template = new OdtTemplate(__DIR__ . '/templates/template_04_metadata.odt');

// [2] Load the template file
$template->load();

// [3] Set document metadata
$template->setMeta([
    'title' => 'Q2 Financial Report',
    'creator' => 'Anna Example',
    'initial_creator' => 'OdtTemplateEngine Sample',
    'subject' => 'Quarterly Financial Analysis',
    'keywords' => ['finance', 'report', '2025'],
    'language' => 'en',
    'generator' => 'OdtTemplateEngine v1.0',
    'editing_cycles' => 4,
    'editing_duration' => 'PT20M',
    'description' => 'Generated automatically with OdtTemplateEngine.',
    'creation_date' => date(DATE_W3C),
    'date' => date('c'), // current date in ISO 8601 format
]);

// [4] Save the file once to ensure metadata is written into the document
$outputPath = __DIR__ . '/output/output_04_metadata.odt';
$template->save($outputPath);

// === Phase 2: Reload and Process Metadata ===

// [5] Re-open the saved document with a fresh template instance
$template = new OdtTemplate($outputPath);
$template->load();

// [6] Ensure that custom paragraph styles exist
$template->ensureParagraphStylesExist([
    'customParagraph' => [
        'margin-top'       => '0.3cm',
        'margin-bottom'    => '0.3cm',
        'margin-right'     => '8cm',
        'background-color' => '#f7f8fa', // light gray background
        'padding'          => '0.3cm',
        'border'           => '1px dashed #d32f2f',
        'font-family'      => 'Ubuntu',
    ],
    // Additional named styles could be registered here
]);

// [7] Read freshly saved metadata from the document
$metadata = $template->getMeta();

// [8] Define a friendly label mapping and desired display order
$metadataOrder = [
    'title'            => 'Title',
    'creator'          => 'Creator',
    'initial_creator'  => 'Initial creator',
    'subject'          => 'Subject',
    'description'      => 'Description',
    'keywords'         => 'Keywords',
    'language'         => 'Language',
    'creation_date'    => 'Creation date',
    'generator'        => 'Generated by',
    'editing_cycles'   => 'Editing Cycles',
    'editing_duration' => 'Editing Duration',
    'date'             => 'Document date',
];

// [9] Create a new Paragraph element with the custom style
$metaPar = new Paragraph();
$metaPar->setParagraphStyle('customParagraph');

// [10] Build the Paragraph content from metadata
foreach ($metadataOrder as $key => $label) {
    if (isset($metadata[$key])) {
        $value = is_array($metadata[$key]) ? implode(', ', $metadata[$key]) : $metadata[$key];
        $metaPar
            ->addText($label . ': ', [
                'font-family'=>'Ubuntu',
                'bold'      => true,
                'font-size' => '10pt',
                'color'     => '#d32f2f' // blue for labels
            ])
            ->addText($value, [
                'font'=>'Ubuntu',
                'font-size' => '8pt',
                'color'     => '#000000' // black for values
            ])
            ->addLineBreak();
    }
}

// [11] Insert the completed Paragraph into the template at the placeholder {{metadata}}
$template->setElement('metadata', $metaPar);

// [12] Render the template with all assigned values
$template->render();

// [13] Save the final document
$template->save($outputPath);
